### PR TITLE
LPS-73737 Tests should use publish button instead of save button

### PR DESCRIPTION
**Pull request by inacionery**
Thanks @vicnate5

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
Test Failure is a known issue at head, unrelated to workflow.

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
https://github.com/liferay/com-liferay-portal-workflow/pull/177

**Pull request closed without merging**
