### PR TITLE
LPS-74698 If backURL is not set then go to My Workflow Tasks

### PR DESCRIPTION
**Pull request by natocesarrego**
@dacousalr

### CODE REVIEW

**Comment by natocesarrego** [comment]
Hi,
From what I could see, the CI failure isn't related with the change introduced by this pull.
Thanks.

**Comment by brandizzi** [comment]
ci:retest

**Comment by brandizzi** [comment]
ci:retest

**Comment by brandizzi** [comment]
ci:retest

**Comment by brandizzi** [comment]
@dacousalr @natocesarrego sorry guys, I'm having some failures that may or may not be related to this fix. I'm waiting to have some LRQAs (most notably https://github.com/liferay/com-liferay-portal-workflow/pull/196) to make some last tests before sending it forward.

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
I rebased it and sent for more tests here: https://github.com/liferay/com-liferay-portal-workflow/pull/197 I am really suspicious by this broken test. Let's wait to see the new PR results to proceed.

**Pull request closed without merging**
