### PR TITLE
LPS-70122 SF

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
@inacionery did we miss any baseline?

**Comment by inacionery** [comment]
@marcellustavares i have fixed it at https://github.com/liferay/com-liferay-portal-workflow/pull/50/commits/cd5d5e352f02c02e6adca140e658f33111597c1a

**Comment by marcellustavares** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
these errors are not related

**Pull request merged**
