### PR TITLE
LPS-73734 Remove a test that no longer makes sense.

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
Hey @brandizzi,

Could you please review it?

Thx!

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
Hey @vicnate5,

Private modules must be compiled with the PR code. Could you please help us with this?

Thx!

**Comment by vicnate5** [comment]
@inacionery Version increase needed?

**Comment by inacionery** [comment]
@vicnate5, there is already a commit for this https://github.com/liferay/com-liferay-portal-workflow/pull/215/commits/1aae9ef7dbe72cbdb05726585d973454dad8ea5d

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
Forwarded to https://github.com/liferay/com-liferay-portal-workflow/pull/237

**Pull request closed without merging**
