### PR TITLE
com-liferay-portal-workflow javadoc

### PR DESCRIPTION
**Pull request by jeyvison**
https://issues.liferay.com/browse/LRDOCS-4264, As we discussed, I created a ticket to clear out some @review tags in the repo. Please review before merging. cc @inacionery

### CODE REVIEW

**Comment by jeyvison** [comment]
hey @rafaprax , Can you take a look at this one please? Thanks :)

**Comment by inacionery** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54641. [See changes here.](https://github.com/brianchandotcom/liferay-portal/compare/c891804~1...c891804)

**Comment by inacionery** [comment]
ci:close

**Pull request closed without merging**
