### PR TITLE
LPS-70158 Trim all elements in Workflow XML parsing

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by marcellustavares** [comment]
@inacionery, please avoid to merge your own PRs, assign it to @brandizzi or me to approve and merge. 

Thanks

**Comment by daviddotzhang** [comment]
@marcellustavares  @inacionery  may I know the status of the issue ?

**Comment by inacionery** [comment]
Hi @daviddotzhang,

We are waiting the merge to the central https://github.com/liferay/liferay-portal/pull/1286, but the CI is failing ☹️ 

When it's merged, i'll change the status of issue.

Thx!

**Comment by inacionery** [comment]
Hey @daviddotzhang,

It's merged!

**Pull request merged**
