### PR TITLE
LPS-72859

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:retest

**Comment by daviddotzhang** [comment]
@inacionery , as https://issues.liferay.com/browse/LPS-72014 is not implemented yet, so we need to avoid inconsistent behavior,  if we keep the autotranslation in workflow task, this is confusing?

what is your idea, do you want to keep it as the behavior now?

**Comment by inacionery** [comment]
Hey @marcellustavares,

What do you think? Should we remove the automatic translation or keep?

Thx!

**Comment by daviddotzhang** [comment]
@marcellustavares  could you help on "Should we remove the automatic translation or keep?"

**Comment by daviddotzhang** [comment]
@marcellustavares @inacionery 
CSE accepted this as a feature request. thanks

**Pull request closed without merging**
