### PR TITLE
LPS-74645 Update the tests

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test

**Comment by inacionery** [comment]
ci:test

**Comment by vicnate5** [comment]
@inacionery Looks like the Double Approver test needs 1 more update. Still expecting to find the definition by the name (not the title)? https://github.com/liferay/com-liferay-portal-workflow/blob/master/portal-workflow-kaleo-test/src/testFunctional/tests/WorkflowUsecase.testcase#L466

Are we never using the "name" in the UI at all?

**Comment by inacionery** [comment]
Yes, we removed the name from UI.
@vicnate5

**Comment by inacionery** [comment]
ci:test

**Pull request merged**
