### PR TITLE
LPS-73480

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by yuhai** [comment]
Hi team,

The test is for https://github.com/sergiogonzalez/liferay-portal/pull/3950 using.

Regards,
Hai

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
Hi @yuhai,

We'll need to wait for the fix to be merged into master to continue the revision of this PR. For now we'll let it on hold.

Thx!

**Comment by yuhai** [comment]
Hi @inacionery 

The portal has been merged from https://github.com/brianchandotcom/liferay-portal/pull/50646. Could you please review the test method when you have free time?

Regards,
Hai

**Comment by inacionery** [comment]
ci:retest

**Comment by yuhai** [comment]
Hi @inacionery 

Hope you are well.

Since the issue came from EE customer. Could you please review this PR when you have time?

Regards,
Hai

**Comment by inacionery** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
Forwarded to #116

**Pull request closed without merging**
