### PR TITLE
LPS-76008 / LPS-73731 SF.

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:retest

**Comment by brandizzi** [comment]
ci:retest <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
@pcwhite Apparently these Calendar failures are not related, they are
popping up in different PRs. I could not reproduce it locally. Is this a
known glitch?

**Comment by vicnate5** [comment]
@brandizzi One of these failures is a known issue that was already fixed at head. The other issue needs to be fixed on the test. I am going to take care of that right now.

Neither issue is due to this PR.

CC @pcwhite

**Comment by vicnate5** [comment]
@brandizzi Actually, one of the failures here is unique to the pull.

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
I will look at these failures when I get in tomorrow.

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
@brandizzi Looks good now.

**Pull request merged**
