### PR TITLE
LRQA-35645 | master

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-35726
https://issues.liferay.com/browse/LRQA-35645

Added an additional unrelated test fix here

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
removed my extra commit because it did not fix the problem

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Pull request merged**
