### PR TITLE
LPS-67908 Only send message after tx commit

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Pushed upstream

**Comment by shuyangzhou** [comment]
CC @marcellus this is fixing the massive CI failures on portal master.

**Comment by shuyangzhou** [comment]
CC @marcellustavares this is fixing the massive CI failures on portal master.

**Comment by marcellustavares** [comment]
Thx @shuyangzhou

**Comment by marcellustavares** [comment]
@shuyangzhou, do you how the tests passed in the first place? both in the subrepo and in ci-merge pull?

**Comment by shuyangzhou** [comment]
@marcellustavares It is a race condition, so it could be that it was really lucky.but I doubt that, my best guess is , the pull was not tested on the correct branch at all. It happened before. @brianchandotcom and I will check with qa this afternoon.

**Comment by jpince** [comment]
@shuyangzhou is something else needed to complete the fix?
```

    [junit] Testcase: testScanXMLLog(com.liferay.portal.log.assertor.PortalLogAssertorTest):	FAILED
    [junit] 
    [junit] Portal log assert failure, see above log for more information: 
    [junit] Unable to execute transaction commit callback
    [junit] com.liferay.portal.kernel.exception.ModelListenerException: java.lang.NullPointerException
```
https://test-1-3.liferay.com/job/test-subrepository-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/65/consoleFull

**Comment by shuyangzhou** [comment]
@jpince this is a separate issue, I will fix it in another pull, then workflow will be fine, then we can retest journal. Their issues are all messed up together, although they are technically not related.

**Comment by shuyangzhou** [comment]
@jpince the fix is at https://github.com/liferay/com-liferay-portal-workflow/commit/58699319c3735d8ad8a36c90870cc5c0b0fc9536

**Comment by jpince** [comment]
Thanks @shuyangzhou

**Pull request merged**
