### PR TITLE
LPS-76296 SF

### PR DESCRIPTION
**Pull request by linolaoj**
cc/ @pcwhite

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test

**Comment by inacionery** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
Hey @linolaoj, the following changes are missing: the name of the definition on top of details info, change the Details and Revision History tabs for navigation and the fonts used following the Invision Prototype. Thanks!

**Comment by linolaoj** [comment]
Hi @inacionery , here it is https://github.com/liferay/com-liferay-portal-workflow/pull/278 
It might still need some css adjustments, let me know what you think. 
Thanks!

**Pull request closed without merging**
