### PR TITLE
LRQA-36538 | master

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-36538

cc @vicnate5

### CODE REVIEW

**Comment by vicnate5** [comment]
The tests did not like the change :(

**Comment by anthony-chu** [comment]
thanks @vicnate5. fixed the spelling error

**Comment by anthony-chu** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:retest

**Comment by vicnate5** [comment]
@anthony-chu Does this need additional navigation updates?

**Comment by anthony-chu** [comment]
hey @vicnate5, yea it needs some navigation updates. i'll update this pull with the navigation update.

**Comment by anthony-chu** [comment]
ci:retest

**Comment by vicnate5** [comment]
@inacionery This is good now. Failure is not related.

**Pull request merged**
