### PR TITLE
LPS-73191 Check the success message

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
Hey @brandizzi there are some changes I still need to make in this PR, so I'll close it for now.

**Comment by brandizzi** [comment]
The failure is recurring on the last days: https://testray.liferay.com/home/-/testray/case_results/145082037/history?tab=result

**Pull request closed without merging**
