### PR TITLE
LRQA-36534 | master

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-36534

cc @vicnate5

### CODE REVIEW

**Comment by anthony-chu** [comment]
test failures caused by [LPS-76281](https://issues.liferay.com/browse/LPS-76281).

**Comment by inacionery** [comment]
ci:retest

**Comment by anthony-chu** [comment]
test failure caused by [LPS-76309](https://issues.liferay.com/browse/LPS-76309).

**Comment by vicnate5** [comment]
@inacionery See Anthony's comment, test failures not related.

**Pull request merged**
