### PR TITLE
LPS-69997 Use a version instead of a project

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
Hey @hhuijser @pyoo47,

This error of SF is not an issue with the code, could you please help me with that?

Thx!

**Comment by pyoo47** [comment]
@inacionery This is a problem within sourceFormatter itself. @Ithildir is currently working on a fix.

**Comment by Ithildir** [comment]
@inacionery and @pyoo47, this is the pull with the fix: https://github.com/brianchandotcom/liferay-portal/pull/48791

**Comment by inacionery** [comment]
Thx! @pyoo47 and @ithildir

**Comment by jpince** [comment]
ci:retest

**Comment by Ithildir** [comment]
@jpince: when using `latest.release` in Gradle, the version is cached for 24 hours. Maybe that's what is happening: the CI slaves still think the previous (bugged) version is the latest one. We could probably add the `--refresh-dependencies` argument every time we invoke Gradle in a subrepo.

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
@Ithildir thanks for your help. Peter said it was something BChan had to update after merging your pull (I retested too soon!)

@inacionery thanks for your patience as we work to keep our CI tests passing

**Comment by inacionery** [comment]
thx! @jpince

**Pull request merged**
