### PR TITLE
LPS-73738

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test

**Comment by vicnate5** [comment]
Bug causing most of these failures was fixed at head, if you can retest tomorrow, that would be best.

**Comment by inacionery** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
Forwarded to https://github.com/liferay/com-liferay-portal-workflow/pull/275

**Pull request closed without merging**
