### PR TITLE
LPS-73191 not showing unpublish option for unpublished definition

### PR DESCRIPTION
**Pull request by linolaoj**
cc/ @pcwhite

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test

**Comment by vicnate5** [comment]
Test Failures are known issues, not related to this pull.

**Comment by inacionery** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Hi @inacionery, I'm going to update the confirm messages and push the changes.
Thanks!

**Comment by inacionery** [comment]
ci:test

**Comment by inacionery** [comment]
@pcwhite

**Comment by inacionery** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
Closed to perform the changes described here https://issues.liferay.com/browse/LPS-73191?focusedCommentId=1220508&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1220508

**Pull request closed without merging**
