### PR TITLE
LPS-75321 | master

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LPS-75321

/cc @vicnate5 @ealonso 

These seem to be the only acceptance tests in Workflow that are blocking LPS-75321 from being merged. The fix to be applied after should be pretty simple.

### CODE REVIEW

**Comment by vicnate5** [comment]
Thanks @anthony-chu

**Comment by inacionery** [comment]
ci:retest

**Comment by ealonso** [comment]
Hey @anthony-chu, @vicnate5, @inacionery,

Since https://github.com/brianchandotcom/liferay-portal/pull/53018 was merged on master, I think the best solution for that is fixed the broken tests instead of add those tests to "quarantine".

Regards,
Eudaldo.

**Comment by vicnate5** [comment]
Will fix the broken tests https://issues.liferay.com/browse/LRQA-36151

**Pull request closed without merging**
