### PR TITLE
LPS-73909

### PR DESCRIPTION
**Pull request by jeyvison**
cc: @pcwhite 

This **can't be merged** into subrepo before [this PR](https://github.com/brianchandotcom/liferay-portal/pull/53933) is merged into central.

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test

**Comment by jeyvison** [comment]
ci:retest

**Comment by jeyvison** [comment]
ci:close

**Comment by jeyvison** [comment]
ci:reopen

**Comment by inacionery** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
Hey @jeyvison, 

could you please follow the behaviour described in the Invision prototype, in the part that you are unpublishing the definition in the editing screen. 

Sending back to you https://github.com/jeyvison/com-liferay-portal-workflow/pull/6. 

Thx!

**Pull request closed without merging**
