### PR TITLE
LPS-70937

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
@brandizzi, let's discuss this issue tomorrow. I have some open questions about it.

Thx

**Comment by arthurchan35** [comment]
Hi @marcellustavares @brandizzi 
Do we have any conclusion yet?

**Comment by inacionery** [comment]
Pull request submitted to https://github.com/liferay/com-liferay-portal-workflow/pull/42

**Pull request closed without merging**
