### PR TITLE
LPS-72227 Not needed anymore

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:stop Waiting until https://github.com/brianchandotcom/liferay-portal/pull/48721 is merged.

**Comment by Ithildir** [comment]
ci:reopen

**Comment by Ithildir** [comment]
ci:retest

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
