### PR TITLE
LPS-72838 Adjust the redirect

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:retest

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Comment by vicnate5** [comment]
@inacionery I cannot reproduce the error on my machine, but CI is getting it consistently
```
    [exec] 19:18:52,422 ERROR [http-nio-8080-exec-6][PortletServlet:111] javax.portlet.PortletException: javax.portlet.PortletException: processAction method not implemented
     [exec] javax.portlet.PortletException: javax.portlet.PortletException: processAction method not implemented
     [exec] 	at com.liferay.portal.kernel.portlet.LiferayPortlet.callActionMethod(LiferayPortlet.java:196)
     [exec] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.callActionMethod(MVCPortlet.java:418)
```

I can follow up with our Jenkins team on Monday.

**Comment by inacionery** [comment]
Hey @vicnate5,

This error is really strange because the JSP is calling the processAction method, but I have removed that call.

Another thing is that the screenshot of POSHI [`<executefunction="AssertClick#pauseAssertTextClickAt"locator1="Button#DONE"value1="Done"/>`](https://testray.liferay.com/reports/production/logs/test-1-13/1497032072014/test-subrepository-acceptance-pullrequest(master)/30/subrepository-functional-tomcat80-mysql56-jdk8/1/0/WorkflowCalendar_ApproveEventWithInvitedUser/index.html.gz), the dialog looks like before my changes. It's like only the backend were deployed.

**Comment by vicnate5** [comment]
Sent some additional test fixes.
https://github.com/brianchandotcom/liferay-portal/pull/49617

Deployment bug will be fixed by https://issues.liferay.com/browse/LRQA-33222

On our test run, the 6.2.3 upgrade test failed. Will need to check into this.

**Comment by vicnate5** [comment]
ci:retest

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
