### PR TITLE
LRQA-34385 Add toggle for LPS-73924

### PR DESCRIPTION
**Pull request by brandizzi**
Retrying #125

### CODE REVIEW

**Comment by brandizzi** [comment]
cc @vicnate5

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
Looks like there is an issue at master head causing this test failure. We have a large group of test failures at head across components due to https://issues.liferay.com/browse/LPS-74199

@brandizzi This is good to merge.

**Comment by brandizzi** [comment]
ci:retest

Since LPS-74199 is marked as resolved and merged, let's try once more.

**Comment by inacionery** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
