### PR TITLE
LPS-73924 | master

### PR DESCRIPTION
**Pull request by brandizzi**
Hey @vicnate5!

While we were working in https://github.com/liferay/com-liferay-portal-workflow/pull/122, something else merged into master and caused a conflict. I just resolved the conflict and sent a new pull request for this issue here.

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
ci:retest

**Comment by brandizzi** [comment]
ci:retest

**Comment by brandizzi** [comment]
ci:stop

**Comment by brandizzi** [comment]
ci:close

I will send it again. Maybe we need a new PR to it to get a newer version of portal.

**Pull request closed without merging**
