### PR TITLE
LPS-71783 Create integration test to Join Xor workflow definition

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
