### PR TITLE
[TS] LPS-76664

### PR DESCRIPTION
**Pull request by dacousalr**
Hi,

Could you review this? It tries to align variable {userName} used in WF templates and profile picture shown in Notifications.

Thanks in advance

https://issues.liferay.com/browse/LPS-76664

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test

**Comment by dacousalr** [comment]
ci:test

**Comment by inacionery** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
Forwarded to https://github.com/liferay/com-liferay-portal-workflow/pull/297

**Pull request closed without merging**
