### PR TITLE
LPS-73924 buildLang

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:retest

**Comment by brandizzi** [comment]
ci:retest

**Comment by vicnate5** [comment]
@brandizzi I am taking a look at the test failures. I think there are more test updates needed.

**Comment by vicnate5** [comment]
ci:close

**Comment by vicnate5** [comment]
continued on https://github.com/liferay/com-liferay-portal-workflow/pull/122

**Pull request closed without merging**
