### PR TITLE
LPS-76315 Create firendly route to avoid url lenght problems

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test

**Comment by inacionery** [comment]
ci:retest

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Re-sent at https://github.com/liferay/com-liferay-portal-workflow/pull/265.

**Pull request closed without merging**
