### PR TITLE
LPS-76316

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jeyvison** [comment]
ci:test

**Comment by jeyvison** [comment]
ci:retest

**Comment by inacionery** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
ci:retest

**Comment by jeyvison** [comment]
ci:stop

**Comment by jeyvison** [comment]
ci:retest

**Comment by jeyvison** [comment]
@pcwhite

**Comment by inacionery** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
Forwarded to https://github.com/liferay/com-liferay-portal-workflow/pull/276

**Pull request closed without merging**
