### PR TITLE
LPS-74391 Calendar and comment box disappear if the modal dialog is closed and reopened

### PR DESCRIPTION
**Pull request by dustinryerson**
This is an update for https://issues.liferay.com/browse/LPS-74391.

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:retest

**Comment by brandizzi** [comment]
Hey @dustinryerson!

How urgent is this? We will have a hackaton here tomorrow and the time is then in short supply :( Also I'd like to check this fix with special attention (it looks good to me but JavaScript is a perilous beast). Can we check it by Monday?

Thanks!

**Comment by dustinryerson** [comment]
Hey @brandizzi!

Thanks for the update. I'm actually working on this right now testing the option of using POST rather than adding in all the JavaScript. I should be able to send a new pull with an updated fix by tonight or tomorrow. I think it's probably ok to check it by Monday. Enjoy the hackathon!

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
ci:retest

**Comment by brandizzi** [comment]
ci:retest

Hey @dustinryerson! Sorry for the delay, I'll check this one by tomorrow.

**Comment by dustinryerson** [comment]
@brandizzi I tried sending a backport for this, but they asked me to wait until this fix is merged into the central https://github.com/liferay/liferay-portal repo https://github.com/liferay/liferay-portal-ee/pull/2411#issuecomment-328919583 - any idea when that will happen? I'd just like to be able to set accurate expectations for CS and the customer.

Thanks!

**Comment by inacionery** [comment]
Hey @dustinryerson,

You can follow the PR of the merge https://github.com/liferay/liferay-portal/pull/1910.

It's a CI dependency, not ours.

Thx!

**Comment by dustinryerson** [comment]
Thank you, @inacionery!

**Comment by gergelyszaz** [comment]
Hi @inacionery,

https://github.com/liferay/liferay-portal/pull/1910 was closed and the changes are not merged to master. Could you please check that?

As a side note I think your username is not correct in [ci.properties](https://github.com/liferay/com-liferay-portal-workflow/blob/aadf0f957ce8d691e292b9966bd52440e377ed0d/ci.properties).

Thanks.

**Comment by inacionery** [comment]
Hi @gergelyszaz,

Every time we merge something into the subrepo, the CI automatically opens a PR to merge it in the central, if it has some other PR open it also automatically closes the old one. The last PR is this https://github.com/liferay/liferay-portal/pull/1919, but it is failing with unrelated tests.

Thanks for getting this.

**Pull request merged**
