### PR TITLE
LPS-72558

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @joshuacords

### CODE REVIEW

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
Hi @joshuacords,

These changes do not fix the issue of [LPS-72558]( https://issues.liferay.com/browse/LPS-72558).I saw the [LPP-25355](https://issues.liferay.com/browse/LPP-25355) and the fix for it was already made in [LPS-56153](https://issues.liferay.com/browse/LPS-56153), but the backport ([BPR-4046](https://issues.liferay.com/browse/BPR-4046)) to 6.2.x is not complete.

For now i'll close this pull request.

Thanks!

/cc @jonathanmccann @SamZiemer

**Comment by joshuacords** [comment]
Hello @inacionery, I see that the BPR of LPS-56153 does solve the null-pointer issue in 6.2.x, however I am also fixing the other issue on the ticket. In master when following the steps in LPS-72558 a bad notification will be sent; this PR attempts to correct that problem in master. In 6.2.x both the BPR and this fix are needed to solve the two parts of the issue. My understanding is this code change is necessary, can this PR be reopened or is there an alternative way I should pursue?
@jonathanmccann @SamZiemer

**Comment by inacionery** [comment]
Hi @joshuacords,

I tested this change, but I'm still getting the bad notification. Could you please double check it and resend?

Thx!

**Comment by joshuacords** [comment]
Hi @inacionery,
I checked with a new version of master and my changes are working. I'm going to send up a new PR based on the newer version of master. 
@jonathanmccann @SamZiemer

**Pull request closed without merging**
