### PR TITLE
LPS-71182 - If workflow assigns by Organization Role, and the workflow is applied to a regular site, user with organization role should not be notified

### PR DESCRIPTION
**Pull request by daviddotzhang**

### CODE REVIEW

**Comment by inacionery** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
This is a expected behaviour, please see: https://issues.liferay.com/browse/LPS-21336?focusedCommentId=148060&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-148060

**Comment by daviddotzhang** [comment]
@inacionery  just want to double confirm with you, 

the reproduced step “(10) User1 should receive the blog for approval in their workflow tasks”

does it mean the user1 can view it, but user1 can not assign it to himself?  currently, he can not assign to himself.

**Comment by inacionery** [comment]
Hey @daviddotzhang,

We talked about this issue and generated a lot of questions, for now I'll assign it to myself and soon I have a solution I'll let you know.

Thx!

**Comment by daviddotzhang** [comment]
@inacionery  May I know how are the fix going and the estimated time of the fix ?

**Comment by inacionery** [comment]
Hi @daviddotzhang, i'm waiting an answer from Michael Han.

**Comment by samuelkong** [comment]
Hi @inacionery
Have we gotten any word from Mike?

**Comment by inacionery** [comment]
Hi @samuelkong and @daviddotzhang,

I spoke with Mike and i'll continue the review.

Thx!

**Comment by inacionery** [comment]
Pull request submitted to https://github.com/liferay/com-liferay-portal-workflow/pull/58 [See changes here.](https://github.com/liferay/com-liferay-portal-workflow/compare/41d9547~1...41d9547)

**Pull request closed without merging**
