### PR TITLE
LPS-71783 Auto assign the Kaleo Task Assignment Instance to the user when are completing the Task.

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by marcellustavares** [comment]
I think this is a regression related to @brandizzi pull request.

**Comment by marcellustavares** [comment]
can you add tests for this @inacionery?

**Comment by inacionery** [comment]
@marcellustavares, i'll pushing some integration tests.

**Comment by inacionery** [comment]
@marcellustavares done!

**Comment by inacionery** [comment]
ci:retest

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Comment by brandizzi** [comment]
ci:retest

**Comment by brandizzi** [comment]
ci:retest

**Comment by inacionery** [comment]
closed to resent

**Pull request closed without merging**
