### PR TITLE
LPS-75719 Move exported packages to new portal-workflow-api module.

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
Hey @vicnate5, could you please check if these errors are related to the PR? Thx!

**Comment by vicnate5** [comment]
@inacionery It looks OK. The Workflow upgrade tests are currently flaky, so this failure is not related to this pull.

 I am tracking the fix for the tests at https://issues.liferay.com/browse/LRQA-35645

**Pull request merged**
